### ISSUE TITLE
Blank page menu bugs

### ISSUE THREAD

**Issue by Jess-Izen** [Cog-Bike/cog-bike#37]
From candlestick:  
I'm getting an error/blank page when adding an adding an add on category to the arepas menu of pica pica. It happens with all the arepas that I included a traditional white or sweet yellow add on. 

same error - when trying to click on the "cachapas" item in the pica pica "food" menu 

que pasa?

**Comment by Jess-Izen** [comment]
***this may not need attention anymore, it's only on that one client which they made a long time ago and no longer even operates. might be a legacy database thing.
i'll let you know if it comes up elsewhere

**Comment by WebD00D** [comment]
When selecting add-ons for menu items, there was a note that said if all add-ons in a category are NOT selected, then they'll display. This isn't the case, and there's too much going on there now for me to revert to that. I've updated the copy, but we'll need to make sure couriers know that you do need to select any add ons items you want to use.
