### ISSUE TITLE
Warning showing that order is pickup only and won't be delivered even when delivery is enabled

### ISSUE THREAD

**Issue by Jess-Izen** [Cog-Bike/cog-bike#41]
Order goes through fine, hits twinjet, etc, but there is a confusing warning at checkout
Tested with local jerk - chausseurs

**Comment by WebD00D** [comment]
@Jess-Izen - Delivery could be enabled, but there is a potential the current time was out of range?
<img width="614" alt="Screen Shot 2019-08-28 at 6 10 25 PM" src="https://user-images.githubusercontent.com/12498742/63902595-2187df80-c9bf-11e9-8f53-558fcd0ffbca.png">

**Comment by WebD00D** [comment]
We'll need to verify they have times set for both then if they are not a pickup only courier.
<img width="657" alt="Screen Shot 2019-08-28 at 6 15 26 PM" src="https://user-images.githubusercontent.com/12498742/63902792-e2a65980-c9bf-11e9-9252-ed08cec4dd31.png">

**Comment by WebD00D** [comment]
Okay - so although they had nothing set, my code was still returning falsey. I'll go ahead an update this and make sure it displays an option by default if they are not a pickup only merchant and their times have not been set.
