### ISSUE TITLE
Can't create merchants

### ISSUE THREAD

**Issue by Jess-Izen** [Cog-Bike/cog-bike#64]
Chausseurs:
It seems we can’t create new merchants anymore? It immediately redirects back to the homepage (customer facing), says merchant has been successfully created, but it isn’t added to the list.

**Comment by WebD00D** [comment]
I tested this out on their instance and had no problem. Only issue I'm thinking they are running into is not using a unique email or weak password. Even if it failed, it would still redirect and notify them that it was successful... I updated this to have better error handling and give a reason as to why something isn't working (email/pass issues)
