### ISSUE TITLE
viewing add-ons in merchant menu

### ISSUE THREAD

**Issue by Jess-Izen** [Cog-Bike/cog-bike#8]
not sure how far you are on the menu display side of things, but currently food items only have an 'add to cart' button. this doesn't allow the user to interact with any of the add-on options. i'd recommend showing item options through expanding the section, though a popup or new page would work as well.

**Comment by WebD00D** [comment]
@Jess-Izen Yup! This has been pushed up now. Take a look when you get a chance. 

Side note: You'll see as you add to cart, it just adds them to a list with a grand total to the top of the page. This is not permanent just haven't build the cart component yet, so it just lives as list atm.
